COMMENT ON COLUMN gdx2.file.f_path IS 'Полный путь к файлу';
COMMENT ON COLUMN gdx2.file.f_folder IS 'Папка с файлом';
COMMENT ON COLUMN gdx2.file.f_name IS 'Имя файла полное';
COMMENT ON COLUMN gdx2.file.f_name IS 'Имя файла';
COMMENT ON COLUMN gdx2.file.f_ext IS 'Расширение';
COMMENT ON COLUMN gdx2.file.f_root IS 'Источник';
COMMENT ON COLUMN gdx2.file.f_size IS 'Размер';
COMMENT ON COLUMN gdx2.file.f_ctime IS 'Дата создания';
COMMENT ON COLUMN gdx2.file.f_mtime IS 'Дата модификации';
COMMENT ON COLUMN gdx2.file.f_atime IS 'Дата доступа';
COMMENT ON COLUMN gdx2.file.f_path_md5 IS 'Хеш пути';
COMMENT ON COLUMN gdx2.file.f_text IS 'Текст';
COMMENT ON COLUMN gdx2.file.ngp IS 'НГ Провинция';
COMMENT ON COLUMN gdx2.file.ngo IS 'НГ Область';
COMMENT ON COLUMN gdx2.file.ngr IS 'НГ Район';
COMMENT ON COLUMN gdx2.file.field IS 'Месторождение';
COMMENT ON COLUMN gdx2.file.areaoil IS 'Площадь';
COMMENT ON COLUMN gdx2.file.lu IS 'Лицензионный участок';
COMMENT ON COLUMN gdx2.file.lu_num IS 'Номер ЛУ';
COMMENT ON COLUMN gdx2.file.well IS 'Скважина';
COMMENT ON COLUMN gdx2.file.lat IS 'Координаты - lat';
COMMENT ON COLUMN gdx2.file.lon IS 'Координаты  - lon';
COMMENT ON COLUMN gdx2.file.report_id IS 'Идентификатор отчета';
COMMENT ON COLUMN gdx2.file.report_name IS 'Имя отчета';
COMMENT ON COLUMN gdx2.file.report_text IS 'Текст отчета';
COMMENT ON COLUMN gdx2.file.report_author IS 'Автор отчета';
COMMENT ON COLUMN gdx2.file.report_year IS 'Дата отчета';
COMMENT ON COLUMN gdx2.file.report_tgf IS 'ТГФ';
COMMENT ON COLUMN gdx2.file.dog_zakaz IS 'Договор';
COMMENT ON COLUMN gdx2.file.dog_name IS 'Название договора';
COMMENT ON COLUMN gdx2.file.dog_num IS 'Номер договора';
COMMENT ON COLUMN gdx2.file.dog_date IS 'Дата договора';
COMMENT ON COLUMN gdx2.file.dog_isp IS 'Исполнитель';
COMMENT ON COLUMN gdx2.file.dog_rep IS 'Отчет по договору';
COMMENT ON COLUMN gdx2.file.dog_prikaz IS 'Приказ';
COMMENT ON COLUMN gdx2.file.is_deleted IS 'Удален';
COMMENT ON COLUMN gdx2.file.lastupdate IS 'Дата последнего обновления';
