COMMENT ON COLUMN gdx2.file.f_path IS 'Полный путь к файлу';
COMMENT ON COLUMN gdx2.file.f_folder IS 'Папка с файлом';
COMMENT ON COLUMN gdx2.file.f_name IS 'Имя файла полное';
COMMENT ON COLUMN gdx2.file.f_name IS 'Имя файла';
COMMENT ON COLUMN gdx2.file.f_ext IS 'Расширение';
COMMENT ON COLUMN gdx2.file.f_root IS 'Источник';
COMMENT ON COLUMN gdx2.file.f_size IS 'Размер';
COMMENT ON COLUMN gdx2.file.f_ctime IS 'Дата создания';
COMMENT ON COLUMN gdx2.file.f_mtime IS 'Дата модификации';
COMMENT ON COLUMN gdx2.file.f_atime IS 'Дата доступа';
COMMENT ON COLUMN gdx2.file.f_path_md5 IS 'Хеш пути';
COMMENT ON COLUMN gdx2.file.f_text IS 'Текст';
COMMENT ON COLUMN gdx2.file.ngp IS 'НГ Провинция';
COMMENT ON COLUMN gdx2.file.ngo IS 'НГ Область';
COMMENT ON COLUMN gdx2.file.ngr IS 'НГ Район';
COMMENT ON COLUMN gdx2.file.field IS 'Месторождение';
COMMENT ON COLUMN gdx2.file.areaoil IS 'Площадь';
COMMENT ON COLUMN gdx2.file.lu IS 'Лицензионный участок';
COMMENT ON COLUMN gdx2.file.lu_num IS 'Номер ЛУ';
COMMENT ON COLUMN gdx2.file.well IS 'Скважина';
COMMENT ON COLUMN gdx2.file.lat IS 'Координаты - lat';
COMMENT ON COLUMN gdx2.file.lon IS 'Координаты  - lon';
COMMENT ON COLUMN gdx2.file.report_id IS 'Идентификатор отчета';
COMMENT ON COLUMN gdx2.file.report_name IS 'Имя отчета';
COMMENT ON COLUMN gdx2.file.report_text IS 'Текст отчета';
COMMENT ON COLUMN gdx2.file.report_author IS 'Автор отчета';
COMMENT ON COLUMN gdx2.file.report_year IS 'Дата отчета';
COMMENT ON COLUMN gdx2.file.report_tgf IS 'ТГФ';
COMMENT ON COLUMN gdx2.file.dog_zakaz IS 'Договор';
COMMENT ON COLUMN gdx2.file.dog_name IS 'Название договора';
COMMENT ON COLUMN gdx2.file.dog_num IS 'Номер договора';
COMMENT ON COLUMN gdx2.file.dog_date IS 'Дата договора';
COMMENT ON COLUMN gdx2.file.dog_isp IS 'Исполнитель';
COMMENT ON COLUMN gdx2.file.dog_rep IS 'Отчет по договору';
COMMENT ON COLUMN gdx2.file.dog_prikaz IS 'Приказ';
COMMENT ON COLUMN gdx2.file.is_deleted IS 'Удален';
COMMENT ON COLUMN gdx2.file.lastupdate IS 'Дата последнего обновления';


COMMENT ON TABLE gdx2.field IS 'Месторождения';
COMMENT ON COLUMN gdx2.field.fid IS 'Идентификатор (внутренний)';
COMMENT ON COLUMN gdx2.field.geom IS 'Координаты';
COMMENT ON COLUMN gdx2.field.id IS 'Идентификатор (внутренний)';
COMMENT ON COLUMN gdx2.field."year" IS 'Год открытия';
COMMENT ON COLUMN gdx2.field.tip IS 'Тип';
COMMENT ON COLUMN gdx2.field.areaoil IS 'Название Площади';
COMMENT ON COLUMN gdx2.field.nom IS 'Номер';
COMMENT ON COLUMN gdx2.field.oil IS 'Нефть';
COMMENT ON COLUMN gdx2.field.gas IS 'Газ';
COMMENT ON COLUMN gdx2.field.condensat IS 'Конденсат';
COMMENT ON COLUMN gdx2.field.name_ru IS 'Наименование';
COMMENT ON COLUMN gdx2.field.oblast IS 'Область';
COMMENT ON COLUMN gdx2.field.stadia IS 'Стадия освоения';
COMMENT ON COLUMN gdx2.field.note IS 'Комментарий';
COMMENT ON COLUMN gdx2.field.istochnik IS 'Источник';
COMMENT ON COLUMN gdx2.field.ftype IS 'Тип2';

COMMENT ON TABLE gdx2.lu IS 'Лицензионные участки';
COMMENT ON COLUMN gdx2.lu.fid IS 'Идентификатор (внутренний)';
COMMENT ON COLUMN gdx2.lu.geom IS 'Координаты';
COMMENT ON COLUMN gdx2.lu.id IS 'Идентификатор';
COMMENT ON COLUMN gdx2.lu.areaoil IS 'Площадь';
COMMENT ON COLUMN gdx2.lu.area_lic IS 'Площать ЛУ';
COMMENT ON COLUMN gdx2.lu."year" IS 'Год';
COMMENT ON COLUMN gdx2.lu.nom_zsngp IS 'Номер (ЗСНГП)';
COMMENT ON COLUMN gdx2.lu.nom_list IS 'Номер Листа карты';
COMMENT ON COLUMN gdx2.lu.nom IS 'Номер';
COMMENT ON COLUMN gdx2.lu.data_start IS 'Дата начала';
COMMENT ON COLUMN gdx2.lu.data_end IS 'Дата конца';
COMMENT ON COLUMN gdx2.lu.vid IS 'Вид';
COMMENT ON COLUMN gdx2.lu.ftype IS 'Тип2';
COMMENT ON COLUMN gdx2.lu.name_rus IS 'Наименование';
COMMENT ON COLUMN gdx2.lu.anumber IS 'Номер лицензии';
COMMENT ON COLUMN gdx2.lu.sostiyanie IS 'Состояние';
COMMENT ON COLUMN gdx2.lu.priznak IS 'Признак';
COMMENT ON COLUMN gdx2.lu.nom_lic IS 'Номер Лицензии (полный)';
COMMENT ON COLUMN gdx2.lu.head_nedro IS 'ВИНК';
COMMENT ON COLUMN gdx2.lu.oblast IS 'Область';
COMMENT ON COLUMN gdx2.lu.zngp IS 'ЗСНГП';
COMMENT ON COLUMN gdx2.lu.nedropolz IS 'Недропользователь (полное нименование)';
COMMENT ON COLUMN gdx2.lu.nedropol IS 'Недропользователь (короткое нименование)';
COMMENT ON COLUMN gdx2.lu.nom_urfo IS 'Номер в УРФО';
COMMENT ON COLUMN gdx2.lu.authority IS 'Субъект РФ';


COMMENT ON TABLE gdx2.stp IS 'Отчеты (точки)';
COMMENT ON COLUMN gdx2.stp.id IS 'Идентификатор (внутренний)';
COMMENT ON COLUMN gdx2.stp.geom IS 'Координаты';
COMMENT ON COLUMN gdx2.stp.web_uk_id IS '№';
COMMENT ON COLUMN gdx2.stp.vid_iz IS 'Вид';
COMMENT ON COLUMN gdx2.stp.tgf IS 'ТГФ';
COMMENT ON COLUMN gdx2.stp.n_uk_tgf IS '№ ТГФ';
COMMENT ON COLUMN gdx2.stp.n_uk_rosg IS '№ РГФ';
COMMENT ON COLUMN gdx2.stp.name_otch IS 'Отчет';
COMMENT ON COLUMN gdx2.stp.name_otch1 IS 'Отчет (дополнительно)';
COMMENT ON COLUMN gdx2.stp.avts IS 'Автор';
COMMENT ON COLUMN gdx2.stp.god_nach IS 'Год начала';
COMMENT ON COLUMN gdx2.stp.god_end IS 'Год окончания';
COMMENT ON COLUMN gdx2.stp.org_isp IS 'Организация исполнитель';
COMMENT ON COLUMN gdx2.stp.in_n_tgf IS 'инв. № ТГФ';
COMMENT ON COLUMN gdx2.stp.in_n_rosg IS 'инв. № РГФ';
COMMENT ON COLUMN gdx2.stp.nom_1000 IS 'Лист';
COMMENT ON COLUMN gdx2.stp."method" IS 'Метод';
COMMENT ON COLUMN gdx2.stp."scale" IS 'Масштаб';


COMMENT ON TABLE gdx2.stl IS 'Отчеты (линии)';
COMMENT ON COLUMN gdx2.stl.id IS 'Идентификатор (внутренний)';
COMMENT ON COLUMN gdx2.stl.geom IS 'Координаты';
COMMENT ON COLUMN gdx2.stl.web_uk_id IS '№';
COMMENT ON COLUMN gdx2.stl.vid_iz IS 'Вид';
COMMENT ON COLUMN gdx2.stl.tgf IS 'ТГФ';
COMMENT ON COLUMN gdx2.stl.n_uk_tgf IS '№ ТГФ';
COMMENT ON COLUMN gdx2.stl.n_uk_rosg IS '№ РГФ';
COMMENT ON COLUMN gdx2.stl.name_otch IS 'Отчет';
COMMENT ON COLUMN gdx2.stl.name_otch1 IS 'Отчет (дополнительно)';
COMMENT ON COLUMN gdx2.stl.avts IS 'Автор';
COMMENT ON COLUMN gdx2.stl.god_nach IS 'Год начала';
COMMENT ON COLUMN gdx2.stl.god_end IS 'Год окончания';
COMMENT ON COLUMN gdx2.stl.org_isp IS 'Организация исполнитель';
COMMENT ON COLUMN gdx2.stl.in_n_tgf IS 'инв. № ТГФ';
COMMENT ON COLUMN gdx2.stl.in_n_rosg IS 'инв. № РГФ';
COMMENT ON COLUMN gdx2.stl.nom_1000 IS 'Лист';
COMMENT ON COLUMN gdx2.stl."method" IS 'Метод';
COMMENT ON COLUMN gdx2.stl."scale" IS 'Масштаб';

COMMENT ON TABLE gdx2.sta IS 'Отчеты (полигоны)';
COMMENT ON COLUMN gdx2.sta.id IS 'Идентификатор (внутренний)';
COMMENT ON COLUMN gdx2.sta.geom IS 'Координаты';
COMMENT ON COLUMN gdx2.sta.web_uk_id IS '№';
COMMENT ON COLUMN gdx2.sta.vid_iz IS 'Вид';
COMMENT ON COLUMN gdx2.sta.tgf IS 'ТГФ';
COMMENT ON COLUMN gdx2.sta.n_uk_tgf IS '№ ТГФ';
COMMENT ON COLUMN gdx2.sta.n_uk_rosg IS '№ РГФ';
COMMENT ON COLUMN gdx2.sta.name_otch IS 'Отчет';
COMMENT ON COLUMN gdx2.sta.name_otch1 IS 'Отчет (дополнительно)';
COMMENT ON COLUMN gdx2.sta.avts IS 'Автор';
COMMENT ON COLUMN gdx2.sta.god_nach IS 'Год начала';
COMMENT ON COLUMN gdx2.sta.god_end IS 'Год окончания';
COMMENT ON COLUMN gdx2.sta.org_isp IS 'Организация исполнитель';
COMMENT ON COLUMN gdx2.sta.in_n_tgf IS 'инв. № ТГФ';
COMMENT ON COLUMN gdx2.sta.in_n_rosg IS 'инв. № РГФ';
COMMENT ON COLUMN gdx2.sta.nom_1000 IS 'Лист';
COMMENT ON COLUMN gdx2.sta."method" IS 'Метод';
COMMENT ON COLUMN gdx2.sta."scale" IS 'Масштаб';