"""report tgf

Revision ID: 0e3b12cf3c75
Revises: 1365492eb03a
Create Date: 2024-02-28 22:17:41.419518

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0e3b12cf3c75'
down_revision = '1365492eb03a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.TEXT(), nullable=True),
    sa.Column('search_str', sa.TEXT(), nullable=True),
    sa.Column('addr_ip', sa.String(length=255), nullable=True),
    sa.Column('user_name', sa.String(length=255), nullable=True),
    sa.Column('user_login', sa.String(length=255), nullable=True),
    sa.Column('lastupdate', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='История запросов'
    )
    op.create_index(op.f('ix_history_addr_ip'), 'history', ['addr_ip'], unique=False)
    op.create_index(op.f('ix_history_search_str'), 'history', ['search_str'], unique=False)
    op.create_index(op.f('ix_history_url'), 'history', ['url'], unique=False)
    op.create_index(op.f('ix_history_user_login'), 'history', ['user_login'], unique=False)
    op.create_index(op.f('ix_history_user_name'), 'history', ['user_name'], unique=False)
    # op.drop_table('lu')
    # op.drop_table('field')
    # op.drop_table('spatial_ref_sys')
    op.alter_column('file', 'f_root',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Источник',
               existing_nullable=True)
    op.alter_column('file', 'f_path',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Полный путь к файлу',
               existing_nullable=True)
    op.alter_column('file', 'f_folder',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Папка с файлом',
               existing_nullable=True)
    op.alter_column('file', 'f_name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Имя файла полное',
               existing_nullable=True)
    op.alter_column('file', 'f_ext',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Расширение',
               existing_nullable=True)
    op.alter_column('file', 'f_size',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='Размер',
               existing_nullable=True)
    op.alter_column('file', 'f_ctime',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Дата создания',
               existing_nullable=True)
    op.alter_column('file', 'f_mtime',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Дата модификации',
               existing_nullable=True)
    op.alter_column('file', 'f_atime',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Дата доступа',
               existing_nullable=True)
    op.alter_column('file', 'f_path_md5',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Хеш пути',
               existing_nullable=True)
    op.alter_column('file', 'f_text',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Текст',
               existing_nullable=True)
    op.alter_column('file', 'ngp',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='НГ Провинция',
               existing_nullable=True)
    op.alter_column('file', 'ngo',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='НГ Область',
               existing_nullable=True)
    op.alter_column('file', 'ngr',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='НГ Район',
               existing_nullable=True)
    op.alter_column('file', 'field',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Месторождение',
               existing_nullable=True)
    op.alter_column('file', 'areaoil',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Площадь',
               existing_nullable=True)
    op.alter_column('file', 'lu',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Лицензионный участок',
               existing_nullable=True)
    op.alter_column('file', 'lu_num',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Номер ЛУ',
               existing_nullable=True)
    op.alter_column('file', 'well',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Скважина',
               existing_nullable=True)
    op.alter_column('file', 'lat',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Координаты - lat',
               existing_nullable=True)
    op.alter_column('file', 'lon',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Координаты  - lon',
               existing_nullable=True)
    op.alter_column('file', 'report_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Идентификатор отчета',
               existing_nullable=True)
    op.alter_column('file', 'report_name',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Имя отчета',
               existing_nullable=True)
    op.alter_column('file', 'report_text',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Текст отчета',
               existing_nullable=True)
    op.alter_column('file', 'report_author',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Автор отчета',
               existing_nullable=True)
    op.alter_column('file', 'report_year',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Дата отчета',
               existing_nullable=True)
    op.alter_column('file', 'report_tgf',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='ТГФ',
               existing_nullable=True)
    op.alter_column('file', 'dog_zakaz',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Договор',
               existing_nullable=True)
    op.alter_column('file', 'dog_name',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Название договора',
               existing_nullable=True)
    op.alter_column('file', 'dog_num',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Номер договора',
               existing_nullable=True)
    op.alter_column('file', 'dog_date',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Дата договора',
               existing_nullable=True)
    op.alter_column('file', 'dog_isp',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Исполнитель',
               existing_nullable=True)
    op.alter_column('file', 'dog_rep',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Отчет по договору',
               existing_nullable=True)
    op.alter_column('file', 'dog_prikaz',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Приказ',
               existing_nullable=True)
    op.alter_column('file', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Удален',
               existing_nullable=True)
    op.alter_column('file', 'lastupdate',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Дата последнего обновления',
               existing_nullable=True)
    op.drop_index('file_path_fts_idx', table_name='file')
    op.drop_index('ix_file_geom', table_name='file')
    op.drop_column('file', 'geom')
    op.drop_index('ix_history_task_name', table_name='history_task')
    op.drop_index('ix_history_task_type', table_name='history_task')
    op.create_index(op.f('ix_history_task_task_name'), 'history_task', ['task_name'], unique=False)
    op.create_index(op.f('ix_history_task_task_type'), 'history_task', ['task_type'], unique=False)
    op.add_column('report_tgf', sa.Column('subrf_name', sa.TEXT(), nullable=True))
    op.add_column('report_tgf', sa.Column('list_name', sa.String(length=255), nullable=True))
    op.add_column('report_tgf', sa.Column('part_name', sa.String(length=255), nullable=True))
    op.add_column('report_tgf', sa.Column('areaoil', sa.String(length=255), nullable=True))
    op.add_column('report_tgf', sa.Column('field', sa.String(length=255), nullable=True))
    op.add_column('report_tgf', sa.Column('lu', sa.String(length=255), nullable=True))
    op.add_column('report_tgf', sa.Column('pi_name', sa.TEXT(), nullable=True))
    op.add_column('report_tgf', sa.Column('fin_name', sa.String(length=255), nullable=True))
    op.add_column('report_tgf', sa.Column('org_name', sa.TEXT(), nullable=True))
    op.add_column('report_tgf', sa.Column('zsniigg_report', sa.String(length=255), nullable=True))
    op.add_column('report_tgf', sa.Column('inf_report', sa.String(length=255), nullable=True))
    op.add_column('report_tgf', sa.Column('vid_rab', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_report_tgf_areaoil'), 'report_tgf', ['areaoil'], unique=False)
    op.create_index(op.f('ix_report_tgf_field'), 'report_tgf', ['field'], unique=False)
    op.create_index(op.f('ix_report_tgf_fin_name'), 'report_tgf', ['fin_name'], unique=False)
    op.create_index(op.f('ix_report_tgf_inf_report'), 'report_tgf', ['inf_report'], unique=False)
    op.create_index(op.f('ix_report_tgf_list_name'), 'report_tgf', ['list_name'], unique=False)
    op.create_index(op.f('ix_report_tgf_lu'), 'report_tgf', ['lu'], unique=False)
    op.create_index(op.f('ix_report_tgf_org_name'), 'report_tgf', ['org_name'], unique=False)
    op.create_index(op.f('ix_report_tgf_part_name'), 'report_tgf', ['part_name'], unique=False)
    op.create_index(op.f('ix_report_tgf_pi_name'), 'report_tgf', ['pi_name'], unique=False)
    op.create_index(op.f('ix_report_tgf_subrf_name'), 'report_tgf', ['subrf_name'], unique=False)
    op.create_index(op.f('ix_report_tgf_vid_rab'), 'report_tgf', ['vid_rab'], unique=False)
    op.create_index(op.f('ix_report_tgf_zsniigg_report'), 'report_tgf', ['zsniigg_report'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_tgf_zsniigg_report'), table_name='report_tgf')
    op.drop_index(op.f('ix_report_tgf_vid_rab'), table_name='report_tgf')
    op.drop_index(op.f('ix_report_tgf_subrf_name'), table_name='report_tgf')
    op.drop_index(op.f('ix_report_tgf_pi_name'), table_name='report_tgf')
    op.drop_index(op.f('ix_report_tgf_part_name'), table_name='report_tgf')
    op.drop_index(op.f('ix_report_tgf_org_name'), table_name='report_tgf')
    op.drop_index(op.f('ix_report_tgf_lu'), table_name='report_tgf')
    op.drop_index(op.f('ix_report_tgf_list_name'), table_name='report_tgf')
    op.drop_index(op.f('ix_report_tgf_inf_report'), table_name='report_tgf')
    op.drop_index(op.f('ix_report_tgf_fin_name'), table_name='report_tgf')
    op.drop_index(op.f('ix_report_tgf_field'), table_name='report_tgf')
    op.drop_index(op.f('ix_report_tgf_areaoil'), table_name='report_tgf')
    op.drop_column('report_tgf', 'vid_rab')
    op.drop_column('report_tgf', 'inf_report')
    op.drop_column('report_tgf', 'zsniigg_report')
    op.drop_column('report_tgf', 'org_name')
    op.drop_column('report_tgf', 'fin_name')
    op.drop_column('report_tgf', 'pi_name')
    op.drop_column('report_tgf', 'lu')
    op.drop_column('report_tgf', 'field')
    op.drop_column('report_tgf', 'areaoil')
    op.drop_column('report_tgf', 'part_name')
    op.drop_column('report_tgf', 'list_name')
    op.drop_column('report_tgf', 'subrf_name')
    op.drop_index(op.f('ix_history_task_task_type'), table_name='history_task')
    op.drop_index(op.f('ix_history_task_task_name'), table_name='history_task')
    op.create_index('ix_history_task_type', 'history_task', ['task_type'], unique=False)
    op.create_index('ix_history_task_name', 'history_task', ['task_name'], unique=False)
    op.add_column('file', sa.Column('geom', sa.NullType(), autoincrement=False, nullable=True))
    op.create_index('ix_file_geom', 'file', ['geom'], unique=False)
    op.create_index('file_path_fts_idx', 'file', ['file_path_fts'], unique=False)
    op.alter_column('file', 'lastupdate',
               existing_type=postgresql.TIMESTAMP(),
               comment='Дата последнего обновления',
               existing_nullable=True)
    op.alter_column('file', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               comment='Удален',
               existing_nullable=True)
    op.alter_column('file', 'dog_prikaz',
               existing_type=sa.TEXT(),
               comment='Приказ',
               existing_nullable=True)
    op.alter_column('file', 'dog_rep',
               existing_type=sa.TEXT(),
               comment='Отчет по договору',
               existing_nullable=True)
    op.alter_column('file', 'dog_isp',
               existing_type=sa.TEXT(),
               comment='Исполнитель',
               existing_nullable=True)
    op.alter_column('file', 'dog_date',
               existing_type=postgresql.TIMESTAMP(),
               comment='Дата договора',
               existing_nullable=True)
    op.alter_column('file', 'dog_num',
               existing_type=sa.TEXT(),
               comment='Номер договора',
               existing_nullable=True)
    op.alter_column('file', 'dog_name',
               existing_type=sa.TEXT(),
               comment='Название договора',
               existing_nullable=True)
    op.alter_column('file', 'dog_zakaz',
               existing_type=sa.TEXT(),
               comment='Договор',
               existing_nullable=True)
    op.alter_column('file', 'report_tgf',
               existing_type=sa.TEXT(),
               comment='ТГФ',
               existing_nullable=True)
    op.alter_column('file', 'report_year',
               existing_type=sa.INTEGER(),
               comment='Дата отчета',
               existing_nullable=True)
    op.alter_column('file', 'report_author',
               existing_type=sa.TEXT(),
               comment='Автор отчета',
               existing_nullable=True)
    op.alter_column('file', 'report_text',
               existing_type=sa.TEXT(),
               comment='Текст отчета',
               existing_nullable=True)
    op.alter_column('file', 'report_name',
               existing_type=sa.TEXT(),
               comment='Имя отчета',
               existing_nullable=True)
    op.alter_column('file', 'report_id',
               existing_type=sa.INTEGER(),
               comment='Идентификатор отчета',
               existing_nullable=True)
    op.alter_column('file', 'lon',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Координаты  - lon',
               existing_nullable=True)
    op.alter_column('file', 'lat',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Координаты - lat',
               existing_nullable=True)
    op.alter_column('file', 'well',
               existing_type=sa.VARCHAR(length=255),
               comment='Скважина',
               existing_nullable=True)
    op.alter_column('file', 'lu_num',
               existing_type=sa.VARCHAR(length=255),
               comment='Номер ЛУ',
               existing_nullable=True)
    op.alter_column('file', 'lu',
               existing_type=sa.VARCHAR(length=255),
               comment='Лицензионный участок',
               existing_nullable=True)
    op.alter_column('file', 'areaoil',
               existing_type=sa.VARCHAR(length=255),
               comment='Площадь',
               existing_nullable=True)
    op.alter_column('file', 'field',
               existing_type=sa.VARCHAR(length=255),
               comment='Месторождение',
               existing_nullable=True)
    op.alter_column('file', 'ngr',
               existing_type=sa.VARCHAR(length=255),
               comment='НГ Район',
               existing_nullable=True)
    op.alter_column('file', 'ngo',
               existing_type=sa.VARCHAR(length=255),
               comment='НГ Область',
               existing_nullable=True)
    op.alter_column('file', 'ngp',
               existing_type=sa.VARCHAR(length=255),
               comment='НГ Провинция',
               existing_nullable=True)
    op.alter_column('file', 'f_text',
               existing_type=sa.TEXT(),
               comment='Текст',
               existing_nullable=True)
    op.alter_column('file', 'f_path_md5',
               existing_type=sa.TEXT(),
               comment='Хеш пути',
               existing_nullable=True)
    op.alter_column('file', 'f_atime',
               existing_type=postgresql.TIMESTAMP(),
               comment='Дата доступа',
               existing_nullable=True)
    op.alter_column('file', 'f_mtime',
               existing_type=postgresql.TIMESTAMP(),
               comment='Дата модификации',
               existing_nullable=True)
    op.alter_column('file', 'f_ctime',
               existing_type=postgresql.TIMESTAMP(),
               comment='Дата создания',
               existing_nullable=True)
    op.alter_column('file', 'f_size',
               existing_type=sa.BIGINT(),
               comment='Размер',
               existing_nullable=True)
    op.alter_column('file', 'f_ext',
               existing_type=sa.VARCHAR(length=255),
               comment='Расширение',
               existing_nullable=True)
    op.alter_column('file', 'f_name',
               existing_type=sa.VARCHAR(length=255),
               comment='Имя файла полное',
               existing_nullable=True)
    op.alter_column('file', 'f_folder',
               existing_type=sa.TEXT(),
               comment='Папка с файлом',
               existing_nullable=True)
    op.alter_column('file', 'f_path',
               existing_type=sa.TEXT(),
               comment='Полный путь к файлу',
               existing_nullable=True)
    op.alter_column('file', 'f_root',
               existing_type=sa.TEXT(),
               comment='Источник',
               existing_nullable=True)
    # op.create_table('spatial_ref_sys',
    # sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    # sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.CheckConstraint('srid > 0 AND srid <= 998999', name='spatial_ref_sys_srid_check'),
    # sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    # )
    op.create_table('field',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('geom', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('year', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('tip', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('areaoil', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('nom', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('oil', sa.VARCHAR(length=254), autoincrement=False, nullable=True),
    sa.Column('gas', sa.VARCHAR(length=254), autoincrement=False, nullable=True),
    sa.Column('condensat', sa.VARCHAR(length=254), autoincrement=False, nullable=True),
    sa.Column('name_ru', sa.VARCHAR(length=254), autoincrement=False, nullable=True),
    sa.Column('oblast', sa.VARCHAR(length=254), autoincrement=False, nullable=True),
    sa.Column('stadia', sa.VARCHAR(length=254), autoincrement=False, nullable=True),
    sa.Column('note', sa.VARCHAR(length=254), autoincrement=False, nullable=True),
    sa.Column('istochnik', sa.VARCHAR(length=254), autoincrement=False, nullable=True),
    sa.Column('ftype', sa.VARCHAR(length=8), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='field_pkey')
    )
    op.create_table('lu',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('geom', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('areaoil', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('area_lic', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('year', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('nom_zsngp', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('nom_list', sa.VARCHAR(length=12), autoincrement=False, nullable=True),
    sa.Column('nom', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('data_start', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('data_end', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('vid', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('ftype', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('name_rus', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('anumber', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('sostiyanie', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('priznak', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('nom_lic', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('head_nedro', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('oblast', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('zngp', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('nedropolz', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('nedropol', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('nom_urfo', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('authority', sa.VARCHAR(length=254), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='lu_pkey')
    )
    op.drop_index(op.f('ix_history_user_name'), table_name='history')
    op.drop_index(op.f('ix_history_user_login'), table_name='history')
    op.drop_index(op.f('ix_history_url'), table_name='history')
    op.drop_index(op.f('ix_history_search_str'), table_name='history')
    op.drop_index(op.f('ix_history_addr_ip'), table_name='history')
    op.drop_table('history')
    # ### end Alembic commands ###
