"""create history_task table

Revision ID: 1365492eb03a
Revises: fae1af10a620
Create Date: 2023-12-19 21:19:41.457037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1365492eb03a'
down_revision = 'fae1af10a620'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history_task',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('task_id', sa.String(length=40), nullable=True),
                    sa.Column('task_type', sa.String(length=255), nullable=True),
                    sa.Column('task_name', sa.String(length=255), nullable=True),
                    sa.Column('time_start', sa.TIMESTAMP(), nullable=True),
                    sa.Column('time_end', sa.TIMESTAMP(), nullable=True),
                    sa.Column('time_duration', sa.TIMESTAMP(), nullable=True),
                    sa.Column('lastupdate', sa.TIMESTAMP(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    comment='История задач'
                    )
    op.create_index(op.f('ix_history_task_task_id'), 'history_task', ['task_id'], unique=False)
    op.create_index(op.f('ix_history_task_type'), 'history_task', ['task_type'], unique=False)
    op.create_index(op.f('ix_history_task_name'), 'history_task', ['task_name'], unique=False)


def downgrade() -> None:
    op.drop_index(op.f('ix_history_task_task_id'), table_name='history_task')
    op.drop_index(op.f('ix_history_task_type'), table_name='history_task')
    op.drop_index(op.f('ix_history_task_name'), table_name='history_task')
    op.drop_table('history_task')
