"""add subrf and list

Revision ID: 1793b015268d
Revises: e4f409eae366
Create Date: 2024-03-26 21:16:06.082747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1793b015268d'
down_revision = 'e4f409eae366'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('r_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list_name', sa.String(length=255), nullable=True),
    sa.Column('lastupdate', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='Листы карты'
    )
    op.create_index(op.f('ix_list_list_name'), 'r_list', ['list_name'], unique=False)

    op.create_table('r_subrf',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subrf_name', sa.String(length=255), nullable=True),
    sa.Column('lastupdate', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='Субъекты РФ'
    )
    op.create_index(op.f('ix_subrf_subrf_name'), 'r_subrf', ['subrf_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subrf_subrf_name'), table_name='r_subrf')
    op.drop_table('r_subrf')
    op.drop_index(op.f('ix_list_list_name'), table_name='r_list')
    op.drop_table('r_list')
    # ### end Alembic commands ###
