"""Init

Revision ID: 1c226c3c7cf0
Revises: 
Create Date: 2026-03-17 01:10:40.832954

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1c226c3c7cf0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('field',
    sa.Column('id', sa.Integer(), nullable=False, comment='Идентификатор (внутренний)'),
    sa.Column('year', sa.BigInteger(), nullable=True, comment='Год открытия'),
    sa.Column('tip', sa.String(length=10), nullable=True, comment='Тип'),
    sa.Column('areaoil', sa.Float(), nullable=True, comment='Название Площади'),
    sa.Column('nom', sa.BigInteger(), nullable=True, comment='Номер'),
    sa.Column('oil', sa.String(length=254), nullable=True, comment='Нефть'),
    sa.Column('gas', sa.String(length=254), nullable=True, comment='Газ'),
    sa.Column('condensat', sa.String(length=254), nullable=True, comment='Конденсат'),
    sa.Column('oblast', sa.String(length=254), nullable=True, comment='Область'),
    sa.Column('stadia', sa.String(length=254), nullable=True, comment='Стадия освоения'),
    sa.Column('note', sa.String(length=254), nullable=True, comment='Комментарий'),
    sa.Column('istochnik', sa.String(length=254), nullable=True, comment='Источник'),
    sa.Column('ftype', sa.String(length=8), nullable=True, comment='Тип2'),
    sa.Column('guid', sa.UUID(), nullable=False, comment='Глобальный идентификатор'),
    sa.Column('name_ru', sa.TEXT(), nullable=True, comment='Наименование (рус)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата создания'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата обновления'),
    sa.PrimaryKeyConstraint('id', 'guid'),
    comment='Месторождения'
    )
    op.create_index(op.f('ix_field_name_ru'), 'field', ['name_ru'], unique=False)
    op.create_table('history',
    sa.Column('url', sa.TEXT(), nullable=True),
    sa.Column('search_str', sa.TEXT(), nullable=True),
    sa.Column('addr_ip', sa.String(length=255), nullable=True),
    sa.Column('user_name', sa.String(length=255), nullable=True),
    sa.Column('user_login', sa.String(length=255), nullable=True),
    sa.Column('guid', sa.UUID(), nullable=False, comment='Глобальный идентификатор'),
    sa.Column('name_ru', sa.TEXT(), nullable=True, comment='Наименование (рус)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата создания'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата обновления'),
    sa.PrimaryKeyConstraint('guid'),
    comment='История запросов'
    )
    op.create_index(op.f('ix_history_addr_ip'), 'history', ['addr_ip'], unique=False)
    op.create_index(op.f('ix_history_name_ru'), 'history', ['name_ru'], unique=False)
    op.create_index(op.f('ix_history_search_str'), 'history', ['search_str'], unique=False)
    op.create_index(op.f('ix_history_url'), 'history', ['url'], unique=False)
    op.create_index(op.f('ix_history_user_login'), 'history', ['user_login'], unique=False)
    op.create_index(op.f('ix_history_user_name'), 'history', ['user_name'], unique=False)
    op.create_table('history_task',
    sa.Column('task_id', sa.String(length=40), nullable=True),
    sa.Column('task_type', sa.String(length=255), nullable=True),
    sa.Column('task_name', sa.String(length=255), nullable=True),
    sa.Column('time_start', sa.TIMESTAMP(), nullable=True),
    sa.Column('time_end', sa.TIMESTAMP(), nullable=True),
    sa.Column('time_duration', sa.TIMESTAMP(), nullable=True),
    sa.Column('guid', sa.UUID(), nullable=False, comment='Глобальный идентификатор'),
    sa.Column('name_ru', sa.TEXT(), nullable=True, comment='Наименование (рус)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата создания'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата обновления'),
    sa.PrimaryKeyConstraint('guid'),
    comment='История задач'
    )
    op.create_index(op.f('ix_history_task_name_ru'), 'history_task', ['name_ru'], unique=False)
    op.create_index(op.f('ix_history_task_task_id'), 'history_task', ['task_id'], unique=False)
    op.create_index(op.f('ix_history_task_task_name'), 'history_task', ['task_name'], unique=False)
    op.create_index(op.f('ix_history_task_task_type'), 'history_task', ['task_type'], unique=False)
    op.create_table('lu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('areaoil', sa.Float(), nullable=True, comment='Площадь'),
    sa.Column('area_lic', sa.String(length=10), nullable=True, comment='Площадь ЛУ'),
    sa.Column('year', sa.BigInteger(), nullable=True, comment='Год'),
    sa.Column('nom_zsngp', sa.BigInteger(), nullable=True, comment='Номер (ЗСНГП)'),
    sa.Column('nom_list', sa.String(length=12), nullable=True, comment='Номер Листа карты'),
    sa.Column('nom', sa.BigInteger(), nullable=True, comment='Номер'),
    sa.Column('data_start', sa.TIMESTAMP(), nullable=True, comment='Дата начала'),
    sa.Column('data_end', sa.TIMESTAMP(), nullable=True, comment='Дата конца'),
    sa.Column('vid', sa.String(length=50), nullable=True, comment='Вид'),
    sa.Column('ftype', sa.String(length=5), nullable=True, comment='Тип2'),
    sa.Column('name_rus', sa.String(length=100), nullable=True, comment='Наименование'),
    sa.Column('anumber', sa.String(length=10), nullable=True, comment='Номер лицензии'),
    sa.Column('sostiyanie', sa.String(length=50), nullable=True, comment='Состояние'),
    sa.Column('priznak', sa.String(length=50), nullable=True, comment='Признак'),
    sa.Column('nom_lic', sa.String(length=50), nullable=True, comment='Номер Лицензии (полный)'),
    sa.Column('head_nedro', sa.String(length=100), nullable=True, comment='ВИНК'),
    sa.Column('oblast', sa.String(length=100), nullable=True, comment='Область'),
    sa.Column('zngp', sa.String(length=10), nullable=True, comment='ЗСНГП'),
    sa.Column('nedropolz', sa.String(length=150), nullable=True, comment='Недропользователь (полное наименование)'),
    sa.Column('nedropol', sa.String(length=100), nullable=True, comment='Недропользователь (короткое наименование)'),
    sa.Column('nom_urfo', sa.BigInteger(), nullable=True, comment='Номер в УРФО'),
    sa.Column('authority', sa.String(length=254), nullable=True, comment='Субъект РФ'),
    sa.Column('guid', sa.UUID(), nullable=False, comment='Глобальный идентификатор'),
    sa.Column('name_ru', sa.TEXT(), nullable=True, comment='Наименование (рус)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата создания'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата обновления'),
    sa.PrimaryKeyConstraint('id', 'guid'),
    comment='Лицензионные участки'
    )
    op.create_index(op.f('ix_lu_data_end'), 'lu', ['data_end'], unique=False)
    op.create_index(op.f('ix_lu_name_ru'), 'lu', ['name_ru'], unique=False)
    op.create_table('r_area',
    sa.Column('guid', sa.UUID(), nullable=False, comment='Глобальный идентификатор'),
    sa.Column('name_ru', sa.TEXT(), nullable=True, comment='Наименование (рус)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата создания'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата обновления'),
    sa.PrimaryKeyConstraint('guid'),
    comment='Площади отчетов'
    )
    op.create_index(op.f('ix_r_area_name_ru'), 'r_area', ['name_ru'], unique=False)
    op.create_table('r_author',
    sa.Column('guid', sa.UUID(), nullable=False, comment='Глобальный идентификатор'),
    sa.Column('name_ru', sa.TEXT(), nullable=True, comment='Наименование (рус)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата создания'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата обновления'),
    sa.PrimaryKeyConstraint('guid'),
    comment='Авторы'
    )
    op.create_index(op.f('ix_r_author_name_ru'), 'r_author', ['name_ru'], unique=False)
    op.create_table('r_field',
    sa.Column('guid', sa.UUID(), nullable=False, comment='Глобальный идентификатор'),
    sa.Column('name_ru', sa.TEXT(), nullable=True, comment='Наименование (рус)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата создания'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата обновления'),
    sa.PrimaryKeyConstraint('guid'),
    comment='Месторождения отчетов'
    )
    op.create_index(op.f('ix_r_field_name_ru'), 'r_field', ['name_ru'], unique=False)
    op.create_table('r_list',
    sa.Column('guid', sa.UUID(), nullable=False, comment='Глобальный идентификатор'),
    sa.Column('name_ru', sa.TEXT(), nullable=True, comment='Наименование (рус)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата создания'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата обновления'),
    sa.PrimaryKeyConstraint('guid'),
    comment='Листы карты'
    )
    op.create_index(op.f('ix_r_list_name_ru'), 'r_list', ['name_ru'], unique=False)
    op.create_table('r_lu',
    sa.Column('guid', sa.UUID(), nullable=False, comment='Глобальный идентификатор'),
    sa.Column('name_ru', sa.TEXT(), nullable=True, comment='Наименование (рус)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата создания'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата обновления'),
    sa.PrimaryKeyConstraint('guid'),
    comment='ЛУ отчетов'
    )
    op.create_index(op.f('ix_r_lu_name_ru'), 'r_lu', ['name_ru'], unique=False)
    op.create_table('r_message',
    sa.Column('fio', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('is_done', sa.Boolean(), nullable=True),
    sa.Column('guid', sa.UUID(), nullable=False, comment='Глобальный идентификатор'),
    sa.Column('name_ru', sa.TEXT(), nullable=True, comment='Наименование (рус)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата создания'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата обновления'),
    sa.PrimaryKeyConstraint('guid'),
    comment='Сообщения обратной связи'
    )
    op.create_index(op.f('ix_r_message_email'), 'r_message', ['email'], unique=False)
    op.create_index(op.f('ix_r_message_fio'), 'r_message', ['fio'], unique=False)
    op.create_index(op.f('ix_r_message_name_ru'), 'r_message', ['name_ru'], unique=False)
    op.create_table('r_org',
    sa.Column('guid', sa.UUID(), nullable=False, comment='Глобальный идентификатор'),
    sa.Column('name_ru', sa.TEXT(), nullable=True, comment='Наименование (рус)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата создания'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата обновления'),
    sa.PrimaryKeyConstraint('guid'),
    comment='Организации'
    )
    op.create_index(op.f('ix_r_org_name_ru'), 'r_org', ['name_ru'], unique=False)
    op.create_table('r_pi',
    sa.Column('guid', sa.UUID(), nullable=False, comment='Глобальный идентификатор'),
    sa.Column('name_ru', sa.TEXT(), nullable=True, comment='Наименование (рус)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата создания'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата обновления'),
    sa.PrimaryKeyConstraint('guid'),
    comment='Полезные ископаемые отчетов'
    )
    op.create_index(op.f('ix_r_pi_name_ru'), 'r_pi', ['name_ru'], unique=False)
    op.create_table('r_subrf',
    sa.Column('guid', sa.UUID(), nullable=False, comment='Глобальный идентификатор'),
    sa.Column('name_ru', sa.TEXT(), nullable=True, comment='Наименование (рус)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата создания'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата обновления'),
    sa.PrimaryKeyConstraint('guid'),
    comment='Субъекты РФ'
    )
    op.create_index(op.f('ix_r_subrf_name_ru'), 'r_subrf', ['name_ru'], unique=False)
    op.create_table('r_vid_rab',
    sa.Column('guid', sa.UUID(), nullable=False, comment='Глобальный идентификатор'),
    sa.Column('name_ru', sa.TEXT(), nullable=True, comment='Наименование (рус)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата создания'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата обновления'),
    sa.PrimaryKeyConstraint('guid'),
    comment='Вид работ отчетов'
    )
    op.create_index(op.f('ix_r_vid_rab_name_ru'), 'r_vid_rab', ['name_ru'], unique=False)
    op.create_table('report_tgf',
    sa.Column('folder_root', sa.TEXT(), nullable=True),
    sa.Column('folder_link', sa.TEXT(), nullable=True),
    sa.Column('folder_short', sa.TEXT(), nullable=True),
    sa.Column('folder_name', sa.TEXT(), nullable=True),
    sa.Column('rgf', sa.String(length=255), nullable=True),
    sa.Column('tgf_hmao', sa.String(length=255), nullable=True),
    sa.Column('tgf_ynao', sa.String(length=255), nullable=True),
    sa.Column('tgf_kras', sa.String(length=255), nullable=True),
    sa.Column('tgf_ekat', sa.String(length=255), nullable=True),
    sa.Column('tgf_omsk', sa.String(length=255), nullable=True),
    sa.Column('tgf_novo', sa.String(length=255), nullable=True),
    sa.Column('tgf_tomsk', sa.String(length=255), nullable=True),
    sa.Column('tgf_more', sa.String(length=255), nullable=True),
    sa.Column('tgf_tmn', sa.String(length=255), nullable=True),
    sa.Column('tgf_kurgan', sa.String(length=255), nullable=True),
    sa.Column('tgf', sa.String(length=255), nullable=True),
    sa.Column('report_name', sa.TEXT(), nullable=True),
    sa.Column('author_name', sa.TEXT(), nullable=True),
    sa.Column('year_str', sa.String(length=255), nullable=True),
    sa.Column('year_int', sa.Integer(), nullable=True),
    sa.Column('territory_name', sa.TEXT(), nullable=True),
    sa.Column('subrf_name', sa.TEXT(), nullable=True),
    sa.Column('list_name', sa.TEXT(), nullable=True),
    sa.Column('part_name', sa.TEXT(), nullable=True),
    sa.Column('areaoil', sa.TEXT(), nullable=True),
    sa.Column('field', sa.TEXT(), nullable=True),
    sa.Column('lu', sa.TEXT(), nullable=True),
    sa.Column('pi_name', sa.TEXT(), nullable=True),
    sa.Column('fin_name', sa.TEXT(), nullable=True),
    sa.Column('org_name', sa.TEXT(), nullable=True),
    sa.Column('zsniigg_report', sa.String(length=255), nullable=True),
    sa.Column('inf_report', sa.String(length=255), nullable=True),
    sa.Column('vid_rab', sa.TEXT(), nullable=True),
    sa.Column('comments', sa.TEXT(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('is_alive', sa.Boolean(), nullable=True),
    sa.Column('report_fts', postgresql.TSVECTOR(), nullable=True),
    sa.Column('guid', sa.UUID(), nullable=False, comment='Глобальный идентификатор'),
    sa.Column('name_ru', sa.TEXT(), nullable=True, comment='Наименование (рус)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата создания'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата обновления'),
    sa.PrimaryKeyConstraint('guid'),
    comment='Отчеты ТГФ'
    )
    op.create_index(op.f('ix_report_tgf_areaoil'), 'report_tgf', ['areaoil'], unique=False)
    op.create_index(op.f('ix_report_tgf_author_name'), 'report_tgf', ['author_name'], unique=False)
    op.create_index(op.f('ix_report_tgf_comments'), 'report_tgf', ['comments'], unique=False)
    op.create_index(op.f('ix_report_tgf_field'), 'report_tgf', ['field'], unique=False)
    op.create_index(op.f('ix_report_tgf_fin_name'), 'report_tgf', ['fin_name'], unique=False)
    op.create_index(op.f('ix_report_tgf_folder_link'), 'report_tgf', ['folder_link'], unique=False)
    op.create_index(op.f('ix_report_tgf_folder_name'), 'report_tgf', ['folder_name'], unique=False)
    op.create_index(op.f('ix_report_tgf_folder_root'), 'report_tgf', ['folder_root'], unique=False)
    op.create_index(op.f('ix_report_tgf_folder_short'), 'report_tgf', ['folder_short'], unique=False)
    op.create_index(op.f('ix_report_tgf_inf_report'), 'report_tgf', ['inf_report'], unique=False)
    op.create_index(op.f('ix_report_tgf_list_name'), 'report_tgf', ['list_name'], unique=False)
    op.create_index(op.f('ix_report_tgf_lu'), 'report_tgf', ['lu'], unique=False)
    op.create_index(op.f('ix_report_tgf_name_ru'), 'report_tgf', ['name_ru'], unique=False)
    op.create_index(op.f('ix_report_tgf_org_name'), 'report_tgf', ['org_name'], unique=False)
    op.create_index(op.f('ix_report_tgf_part_name'), 'report_tgf', ['part_name'], unique=False)
    op.create_index(op.f('ix_report_tgf_pi_name'), 'report_tgf', ['pi_name'], unique=False)
    op.create_index(op.f('ix_report_tgf_report_name'), 'report_tgf', ['report_name'], unique=False)
    op.create_index(op.f('ix_report_tgf_rgf'), 'report_tgf', ['rgf'], unique=False)
    op.create_index(op.f('ix_report_tgf_subrf_name'), 'report_tgf', ['subrf_name'], unique=False)
    op.create_index(op.f('ix_report_tgf_territory_name'), 'report_tgf', ['territory_name'], unique=False)
    op.create_index(op.f('ix_report_tgf_tgf'), 'report_tgf', ['tgf'], unique=False)
    op.create_index(op.f('ix_report_tgf_tgf_ekat'), 'report_tgf', ['tgf_ekat'], unique=False)
    op.create_index(op.f('ix_report_tgf_tgf_hmao'), 'report_tgf', ['tgf_hmao'], unique=False)
    op.create_index(op.f('ix_report_tgf_tgf_kras'), 'report_tgf', ['tgf_kras'], unique=False)
    op.create_index(op.f('ix_report_tgf_tgf_kurgan'), 'report_tgf', ['tgf_kurgan'], unique=False)
    op.create_index(op.f('ix_report_tgf_tgf_more'), 'report_tgf', ['tgf_more'], unique=False)
    op.create_index(op.f('ix_report_tgf_tgf_novo'), 'report_tgf', ['tgf_novo'], unique=False)
    op.create_index(op.f('ix_report_tgf_tgf_omsk'), 'report_tgf', ['tgf_omsk'], unique=False)
    op.create_index(op.f('ix_report_tgf_tgf_tmn'), 'report_tgf', ['tgf_tmn'], unique=False)
    op.create_index(op.f('ix_report_tgf_tgf_tomsk'), 'report_tgf', ['tgf_tomsk'], unique=False)
    op.create_index(op.f('ix_report_tgf_tgf_ynao'), 'report_tgf', ['tgf_ynao'], unique=False)
    op.create_index(op.f('ix_report_tgf_vid_rab'), 'report_tgf', ['vid_rab'], unique=False)
    op.create_index(op.f('ix_report_tgf_year_int'), 'report_tgf', ['year_int'], unique=False)
    op.create_index(op.f('ix_report_tgf_year_str'), 'report_tgf', ['year_str'], unique=False)
    op.create_index(op.f('ix_report_tgf_zsniigg_report'), 'report_tgf', ['zsniigg_report'], unique=False)
    op.create_table('sta',
    sa.Column('web_uk_id', sa.String(length=18), nullable=True, comment='№'),
    sa.Column('vid_iz', sa.String(length=26), nullable=True, comment='Вид'),
    sa.Column('tgf', sa.String(length=31), nullable=True, comment='ТГФ'),
    sa.Column('n_uk_tgf', sa.String(length=8), nullable=True, comment='№ ТГФ'),
    sa.Column('n_uk_rosg', sa.String(length=6), nullable=True, comment='№ РГФ'),
    sa.Column('name_otch', sa.String(length=254), nullable=True, comment='Отчет'),
    sa.Column('name_otch1', sa.String(length=254), nullable=True, comment='Отчет (дополнительно)'),
    sa.Column('avts', sa.String(length=254), nullable=True, comment='Автор'),
    sa.Column('god_nach', sa.String(length=4), nullable=True, comment='Год начала'),
    sa.Column('god_end', sa.String(length=4), nullable=True, comment='Год окончания'),
    sa.Column('org_isp', sa.String(length=193), nullable=True, comment='Организация исполнитель'),
    sa.Column('in_n_tgf', sa.String(length=9), nullable=True, comment='инв. № ТГФ'),
    sa.Column('in_n_rosg', sa.String(length=10), nullable=True, comment='инв. № РГФ'),
    sa.Column('nom_1000', sa.String(length=4), nullable=True, comment='Лист'),
    sa.Column('method', sa.String(length=13), nullable=True, comment='Метод'),
    sa.Column('scale', sa.String(length=26), nullable=True, comment='Масштаб'),
    sa.Column('guid', sa.UUID(), nullable=False, comment='Глобальный идентификатор'),
    sa.Column('name_ru', sa.TEXT(), nullable=True, comment='Наименование (рус)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата создания'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата обновления'),
    sa.PrimaryKeyConstraint('guid'),
    comment='Отчеты (полигоны)'
    )
    op.create_index(op.f('ix_sta_name_ru'), 'sta', ['name_ru'], unique=False)
    op.create_table('stl',
    sa.Column('web_uk_id', sa.String(length=18), nullable=True, comment='№'),
    sa.Column('vid_iz', sa.String(length=26), nullable=True, comment='Вид'),
    sa.Column('tgf', sa.String(length=31), nullable=True, comment='ТГФ'),
    sa.Column('n_uk_tgf', sa.String(length=6), nullable=True, comment='№ ТГФ'),
    sa.Column('n_uk_rosg', sa.String(length=6), nullable=True, comment='№ РГФ'),
    sa.Column('name_otch', sa.String(length=254), nullable=True, comment='Отчет'),
    sa.Column('name_otch1', sa.String(length=108), nullable=True, comment='Отчет (дополнительно)'),
    sa.Column('avts', sa.String(length=179), nullable=True, comment='Автор'),
    sa.Column('god_nach', sa.String(length=4), nullable=True, comment='Год начала'),
    sa.Column('god_end', sa.String(length=4), nullable=True, comment='Год окончания'),
    sa.Column('org_isp', sa.String(length=192), nullable=True, comment='Организация исполнитель'),
    sa.Column('in_n_tgf', sa.String(length=6), nullable=True, comment='инв. № ТГФ'),
    sa.Column('in_n_rosg', sa.String(length=6), nullable=True, comment='инв. № РГФ'),
    sa.Column('nom_1000', sa.String(length=4), nullable=True, comment='Лист'),
    sa.Column('method', sa.String(length=13), nullable=True, comment='Метод'),
    sa.Column('scale', sa.String(length=26), nullable=True, comment='Масштаб'),
    sa.Column('guid', sa.UUID(), nullable=False, comment='Глобальный идентификатор'),
    sa.Column('name_ru', sa.TEXT(), nullable=True, comment='Наименование (рус)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата создания'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата обновления'),
    sa.PrimaryKeyConstraint('guid'),
    comment='Отчеты (линии)'
    )
    op.create_index(op.f('ix_stl_name_ru'), 'stl', ['name_ru'], unique=False)
    op.create_table('stp',
    sa.Column('web_uk_id', sa.String(length=18), nullable=True, comment='№'),
    sa.Column('vid_iz', sa.String(length=26), nullable=True, comment='Вид'),
    sa.Column('tgf', sa.String(length=31), nullable=True, comment='ТГФ'),
    sa.Column('n_uk_tgf', sa.String(length=5), nullable=True, comment='№ ТГФ'),
    sa.Column('n_uk_rosg', sa.String(length=6), nullable=True, comment='№ РГФ'),
    sa.Column('name_otch', sa.String(length=254), nullable=True, comment='Отчет'),
    sa.Column('name_otch1', sa.String(length=254), nullable=True, comment='Отчет (дополнительно)'),
    sa.Column('avts', sa.String(length=161), nullable=True, comment='Автор'),
    sa.Column('god_nach', sa.String(length=4), nullable=True, comment='Год начала'),
    sa.Column('god_end', sa.String(length=4), nullable=True, comment='Год окончания'),
    sa.Column('org_isp', sa.String(length=190), nullable=True, comment='Организация исполнитель'),
    sa.Column('in_n_tgf', sa.String(length=7), nullable=True, comment='инв. № ТГФ'),
    sa.Column('in_n_rosg', sa.String(length=6), nullable=True, comment='инв. № РГФ'),
    sa.Column('nom_1000', sa.String(length=4), nullable=True, comment='Лист'),
    sa.Column('method', sa.String(length=13), nullable=True, comment='Метод'),
    sa.Column('scale', sa.String(length=26), nullable=True, comment='Масштаб'),
    sa.Column('guid', sa.UUID(), nullable=False, comment='Глобальный идентификатор'),
    sa.Column('name_ru', sa.TEXT(), nullable=True, comment='Наименование (рус)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата создания'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата обновления'),
    sa.PrimaryKeyConstraint('guid'),
    comment='Отчеты (точки)'
    )
    op.create_index(op.f('ix_stp_name_ru'), 'stp', ['name_ru'], unique=False)
    # op.drop_table('spatial_ref_sys')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('spatial_ref_sys',
    # sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    # sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.CheckConstraint('srid > 0 AND srid <= 998999', name='spatial_ref_sys_srid_check'),
    # sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    # )
    op.drop_index(op.f('ix_stp_name_ru'), table_name='stp')
    op.drop_table('stp')
    op.drop_index(op.f('ix_stl_name_ru'), table_name='stl')
    op.drop_table('stl')
    op.drop_index(op.f('ix_sta_name_ru'), table_name='sta')
    op.drop_table('sta')
    op.drop_index(op.f('ix_report_tgf_zsniigg_report'), table_name='report_tgf')
    op.drop_index(op.f('ix_report_tgf_year_str'), table_name='report_tgf')
    op.drop_index(op.f('ix_report_tgf_year_int'), table_name='report_tgf')
    op.drop_index(op.f('ix_report_tgf_vid_rab'), table_name='report_tgf')
    op.drop_index(op.f('ix_report_tgf_tgf_ynao'), table_name='report_tgf')
    op.drop_index(op.f('ix_report_tgf_tgf_tomsk'), table_name='report_tgf')
    op.drop_index(op.f('ix_report_tgf_tgf_tmn'), table_name='report_tgf')
    op.drop_index(op.f('ix_report_tgf_tgf_omsk'), table_name='report_tgf')
    op.drop_index(op.f('ix_report_tgf_tgf_novo'), table_name='report_tgf')
    op.drop_index(op.f('ix_report_tgf_tgf_more'), table_name='report_tgf')
    op.drop_index(op.f('ix_report_tgf_tgf_kurgan'), table_name='report_tgf')
    op.drop_index(op.f('ix_report_tgf_tgf_kras'), table_name='report_tgf')
    op.drop_index(op.f('ix_report_tgf_tgf_hmao'), table_name='report_tgf')
    op.drop_index(op.f('ix_report_tgf_tgf_ekat'), table_name='report_tgf')
    op.drop_index(op.f('ix_report_tgf_tgf'), table_name='report_tgf')
    op.drop_index(op.f('ix_report_tgf_territory_name'), table_name='report_tgf')
    op.drop_index(op.f('ix_report_tgf_subrf_name'), table_name='report_tgf')
    op.drop_index(op.f('ix_report_tgf_rgf'), table_name='report_tgf')
    op.drop_index(op.f('ix_report_tgf_report_name'), table_name='report_tgf')
    op.drop_index(op.f('ix_report_tgf_pi_name'), table_name='report_tgf')
    op.drop_index(op.f('ix_report_tgf_part_name'), table_name='report_tgf')
    op.drop_index(op.f('ix_report_tgf_org_name'), table_name='report_tgf')
    op.drop_index(op.f('ix_report_tgf_name_ru'), table_name='report_tgf')
    op.drop_index(op.f('ix_report_tgf_lu'), table_name='report_tgf')
    op.drop_index(op.f('ix_report_tgf_list_name'), table_name='report_tgf')
    op.drop_index(op.f('ix_report_tgf_inf_report'), table_name='report_tgf')
    op.drop_index(op.f('ix_report_tgf_folder_short'), table_name='report_tgf')
    op.drop_index(op.f('ix_report_tgf_folder_root'), table_name='report_tgf')
    op.drop_index(op.f('ix_report_tgf_folder_name'), table_name='report_tgf')
    op.drop_index(op.f('ix_report_tgf_folder_link'), table_name='report_tgf')
    op.drop_index(op.f('ix_report_tgf_fin_name'), table_name='report_tgf')
    op.drop_index(op.f('ix_report_tgf_field'), table_name='report_tgf')
    op.drop_index(op.f('ix_report_tgf_comments'), table_name='report_tgf')
    op.drop_index(op.f('ix_report_tgf_author_name'), table_name='report_tgf')
    op.drop_index(op.f('ix_report_tgf_areaoil'), table_name='report_tgf')
    op.drop_table('report_tgf')
    op.drop_index(op.f('ix_r_vid_rab_name_ru'), table_name='r_vid_rab')
    op.drop_table('r_vid_rab')
    op.drop_index(op.f('ix_r_subrf_name_ru'), table_name='r_subrf')
    op.drop_table('r_subrf')
    op.drop_index(op.f('ix_r_pi_name_ru'), table_name='r_pi')
    op.drop_table('r_pi')
    op.drop_index(op.f('ix_r_org_name_ru'), table_name='r_org')
    op.drop_table('r_org')
    op.drop_index(op.f('ix_r_message_name_ru'), table_name='r_message')
    op.drop_index(op.f('ix_r_message_fio'), table_name='r_message')
    op.drop_index(op.f('ix_r_message_email'), table_name='r_message')
    op.drop_table('r_message')
    op.drop_index(op.f('ix_r_lu_name_ru'), table_name='r_lu')
    op.drop_table('r_lu')
    op.drop_index(op.f('ix_r_list_name_ru'), table_name='r_list')
    op.drop_table('r_list')
    op.drop_index(op.f('ix_r_field_name_ru'), table_name='r_field')
    op.drop_table('r_field')
    op.drop_index(op.f('ix_r_author_name_ru'), table_name='r_author')
    op.drop_table('r_author')
    op.drop_index(op.f('ix_r_area_name_ru'), table_name='r_area')
    op.drop_table('r_area')
    op.drop_index(op.f('ix_lu_name_ru'), table_name='lu')
    op.drop_index(op.f('ix_lu_data_end'), table_name='lu')
    op.drop_table('lu')
    op.drop_index(op.f('ix_history_task_task_type'), table_name='history_task')
    op.drop_index(op.f('ix_history_task_task_name'), table_name='history_task')
    op.drop_index(op.f('ix_history_task_task_id'), table_name='history_task')
    op.drop_index(op.f('ix_history_task_name_ru'), table_name='history_task')
    op.drop_table('history_task')
    op.drop_index(op.f('ix_history_user_name'), table_name='history')
    op.drop_index(op.f('ix_history_user_login'), table_name='history')
    op.drop_index(op.f('ix_history_url'), table_name='history')
    op.drop_index(op.f('ix_history_search_str'), table_name='history')
    op.drop_index(op.f('ix_history_name_ru'), table_name='history')
    op.drop_index(op.f('ix_history_addr_ip'), table_name='history')
    op.drop_table('history')
    op.drop_index(op.f('ix_field_name_ru'), table_name='field')
    op.drop_table('field')
    # ### end Alembic commands ###
