"""add area field lu vid_rab

Revision ID: 41731547ce0e
Revises: a3f4bdc6a94c
Create Date: 2024-03-27 22:46:27.641121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41731547ce0e'
down_revision = 'a3f4bdc6a94c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('r_area',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area_name', sa.String(length=255), nullable=True),
    sa.Column('lastupdate', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='Площади отчетов'
    )
    op.create_index(op.f('ix_r_area_area_name'), 'r_area', ['area_name'], unique=False)
    op.create_table('r_field',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=255), nullable=True),
    sa.Column('lastupdate', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='Месторождения отчетов'
    )
    op.create_index(op.f('ix_r_field_field_name'), 'r_field', ['field_name'], unique=False)
    op.create_table('r_lu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lu_name', sa.String(length=255), nullable=True),
    sa.Column('lastupdate', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='ЛУ отчетов'
    )
    op.create_index(op.f('ix_r_lu_lu_name'), 'r_lu', ['lu_name'], unique=False)
    op.create_table('r_pi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pi_name', sa.String(length=255), nullable=True),
    sa.Column('lastupdate', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='Полезные ископаемые отчетов'
    )
    op.create_index(op.f('ix_r_pi_pi_name'), 'r_pi', ['pi_name'], unique=False)
    op.create_table('r_vid_rab',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vid_rab_name', sa.String(length=255), nullable=True),
    sa.Column('lastupdate', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='Вид работ отчетов'
    )
    op.create_index(op.f('ix_r_vid_rab_vid_rab_name'), 'r_vid_rab', ['vid_rab_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_r_vid_rab_vid_rab_name'), table_name='r_vid_rab')
    op.drop_table('r_vid_rab')
    op.drop_index(op.f('ix_r_pi_pi_name'), table_name='r_pi')
    op.drop_table('r_pi')
    op.drop_index(op.f('ix_r_lu_lu_name'), table_name='r_lu')
    op.drop_table('r_lu')
    op.drop_index(op.f('ix_r_field_field_name'), table_name='r_field')
    op.drop_table('r_field')
    op.drop_index(op.f('ix_r_area_area_name'), table_name='r_area')
    op.drop_table('r_area')
    # ### end Alembic commands ###
