"""add spavochniki

Revision ID: 9d515813014d
Revises: e4f409eae366
Create Date: 2024-04-11 22:55:54.679621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d515813014d'
down_revision = 'e4f409eae366'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('r_area',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_ru', sa.String(length=255), nullable=True),
    sa.Column('lastupdate', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='Площади отчетов'
    )
    op.create_index(op.f('ix_r_area_name_ru'), 'r_area', ['name_ru'], unique=False)
    op.create_table('r_author',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_ru', sa.String(length=255), nullable=True),
    sa.Column('lastupdate', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='Авторы'
    )
    op.create_index(op.f('ix_r_author_name_ru'), 'r_author', ['name_ru'], unique=False)
    op.create_table('r_field',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_ru', sa.String(length=255), nullable=True),
    sa.Column('lastupdate', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='Месторождения отчетов'
    )
    op.create_index(op.f('ix_r_field_name_ru'), 'r_field', ['name_ru'], unique=False)
    op.create_table('r_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_ru', sa.String(length=255), nullable=True),
    sa.Column('lastupdate', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='Листы карты'
    )
    op.create_index(op.f('ix_r_list_name_ru'), 'r_list', ['name_ru'], unique=False)
    op.create_table('r_lu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_ru', sa.String(length=255), nullable=True),
    sa.Column('lastupdate', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='ЛУ отчетов'
    )
    op.create_index(op.f('ix_r_lu_name_ru'), 'r_lu', ['name_ru'], unique=False)
    op.create_table('r_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fio', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('name_ru', sa.String(length=255), nullable=True),
    sa.Column('is_done', sa.Boolean(), nullable=True),
    sa.Column('lastupdate', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='Сообщения обратной связи'
    )
    op.create_index(op.f('ix_r_message_email'), 'r_message', ['email'], unique=False)
    op.create_index(op.f('ix_r_message_fio'), 'r_message', ['fio'], unique=False)
    op.create_index(op.f('ix_r_message_name_ru'), 'r_message', ['name_ru'], unique=False)
    op.create_table('r_org',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_ru', sa.String(length=255), nullable=True),
    sa.Column('lastupdate', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='Организации'
    )
    op.create_index(op.f('ix_r_org_name_ru'), 'r_org', ['name_ru'], unique=False)
    op.create_table('r_pi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_ru', sa.String(length=255), nullable=True),
    sa.Column('lastupdate', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='Полезные ископаемые отчетов'
    )
    op.create_index(op.f('ix_r_pi_name_ru'), 'r_pi', ['name_ru'], unique=False)
    op.create_table('r_subrf',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_ru', sa.String(length=255), nullable=True),
    sa.Column('lastupdate', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='Субъекты РФ'
    )
    op.create_index(op.f('ix_r_subrf_name_ru'), 'r_subrf', ['name_ru'], unique=False)
    op.create_table('r_vid_rab',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_ru', sa.String(length=255), nullable=True),
    sa.Column('lastupdate', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='Вид работ отчетов'
    )
    op.create_index(op.f('ix_r_vid_rab_name_ru'), 'r_vid_rab', ['name_ru'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f('ix_r_vid_rab_name_ru'), table_name='r_vid_rab')
    op.drop_table('r_vid_rab')
    op.drop_index(op.f('ix_r_subrf_name_ru'), table_name='r_subrf')
    op.drop_table('r_subrf')
    op.drop_index(op.f('ix_r_pi_name_ru'), table_name='r_pi')
    op.drop_table('r_pi')
    op.drop_index(op.f('ix_r_org_name_ru'), table_name='r_org')
    op.drop_table('r_org')
    op.drop_index(op.f('ix_r_message_name_ru'), table_name='r_message')
    op.drop_index(op.f('ix_r_message_fio'), table_name='r_message')
    op.drop_index(op.f('ix_r_message_email'), table_name='r_message')
    op.drop_table('r_message')
    op.drop_index(op.f('ix_r_lu_name_ru'), table_name='r_lu')
    op.drop_table('r_lu')
    op.drop_index(op.f('ix_r_list_name_ru'), table_name='r_list')
    op.drop_table('r_list')
    op.drop_index(op.f('ix_r_field_name_ru'), table_name='r_field')
    op.drop_table('r_field')
    op.drop_index(op.f('ix_r_author_name_ru'), table_name='r_author')
    op.drop_table('r_author')
    op.drop_index(op.f('ix_r_area_name_ru'), table_name='r_area')
    op.drop_table('r_area')
    # ### end Alembic commands ###
