"""report_tgf

Revision ID: e4f409eae366
Revises: 1365492eb03a
Create Date: 2024-03-06 23:02:43.146225

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e4f409eae366'
down_revision = 'fae1af10a620'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_tgf',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('folder_root', sa.TEXT(), nullable=True),
    sa.Column('folder_link', sa.TEXT(), nullable=True),
    sa.Column('folder_short', sa.TEXT(), nullable=True),
    sa.Column('folder_name', sa.TEXT(), nullable=True),
    sa.Column('rgf', sa.String(length=255), nullable=True),
    sa.Column('tgf_hmao', sa.String(length=255), nullable=True),
    sa.Column('tgf_ynao', sa.String(length=255), nullable=True),
    sa.Column('tgf_kras', sa.String(length=255), nullable=True),
    sa.Column('tgf_ekat', sa.String(length=255), nullable=True),
    sa.Column('tgf_omsk', sa.String(length=255), nullable=True),
    sa.Column('tgf_novo', sa.String(length=255), nullable=True),
    sa.Column('tgf_tomsk', sa.String(length=255), nullable=True),
    sa.Column('tgf_more', sa.String(length=255), nullable=True),
    sa.Column('tgf_tmn', sa.String(length=255), nullable=True),
    sa.Column('tgf_kurgan', sa.String(length=255), nullable=True),
    sa.Column('tgf', sa.String(length=255), nullable=True),
    sa.Column('report_name', sa.TEXT(), nullable=True),
    sa.Column('author_name', sa.TEXT(), nullable=True),
    sa.Column('year_str', sa.String(length=255), nullable=True),
    sa.Column('year_int', sa.Integer(), nullable=True),
    sa.Column('territory_name', sa.TEXT(), nullable=True),
    sa.Column('subrf_name', sa.TEXT(), nullable=True),
    sa.Column('list_name', sa.TEXT(), nullable=True),
    sa.Column('part_name', sa.TEXT(), nullable=True),
    sa.Column('areaoil', sa.TEXT(), nullable=True),
    sa.Column('field', sa.TEXT(), nullable=True),
    sa.Column('lu', sa.TEXT(), nullable=True),
    sa.Column('pi_name', sa.TEXT(), nullable=True),
    sa.Column('fin_name', sa.TEXT(), nullable=True),
    sa.Column('org_name', sa.TEXT(), nullable=True),
    sa.Column('zsniigg_report', sa.String(length=255), nullable=True),
    sa.Column('inf_report', sa.String(length=255), nullable=True),
    sa.Column('vid_rab', sa.TEXT(), nullable=True),
    sa.Column('comments', sa.TEXT(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('is_alive', sa.Boolean(), nullable=True),
    sa.Column('report_fts', postgresql.TSVECTOR(), nullable=True),
    sa.Column('lastupdate', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='Отчеты ТГФ'
    )
    op.create_index(op.f('ix_report_tgf_areaoil'), 'report_tgf', ['areaoil'], unique=False)
    op.create_index(op.f('ix_report_tgf_author_name'), 'report_tgf', ['author_name'], unique=False)
    op.create_index(op.f('ix_report_tgf_comments'), 'report_tgf', ['comments'], unique=False)
    op.create_index(op.f('ix_report_tgf_field'), 'report_tgf', ['field'], unique=False)
    op.create_index(op.f('ix_report_tgf_fin_name'), 'report_tgf', ['fin_name'], unique=False)
    op.create_index(op.f('ix_report_tgf_folder_link'), 'report_tgf', ['folder_link'], unique=False)
    op.create_index(op.f('ix_report_tgf_folder_name'), 'report_tgf', ['folder_name'], unique=False)
    op.create_index(op.f('ix_report_tgf_folder_root'), 'report_tgf', ['folder_root'], unique=False)
    op.create_index(op.f('ix_report_tgf_folder_short'), 'report_tgf', ['folder_short'], unique=False)
    op.create_index(op.f('ix_report_tgf_inf_report'), 'report_tgf', ['inf_report'], unique=False)
    op.create_index(op.f('ix_report_tgf_list_name'), 'report_tgf', ['list_name'], unique=False)
    op.create_index(op.f('ix_report_tgf_lu'), 'report_tgf', ['lu'], unique=False)
    op.create_index(op.f('ix_report_tgf_org_name'), 'report_tgf', ['org_name'], unique=False)
    op.create_index(op.f('ix_report_tgf_part_name'), 'report_tgf', ['part_name'], unique=False)
    op.create_index(op.f('ix_report_tgf_pi_name'), 'report_tgf', ['pi_name'], unique=False)
    op.create_index(op.f('ix_report_tgf_report_name'), 'report_tgf', ['report_name'], unique=False)
    op.create_index(op.f('ix_report_tgf_rgf'), 'report_tgf', ['rgf'], unique=False)
    op.create_index(op.f('ix_report_tgf_subrf_name'), 'report_tgf', ['subrf_name'], unique=False)
    op.create_index(op.f('ix_report_tgf_territory_name'), 'report_tgf', ['territory_name'], unique=False)
    op.create_index(op.f('ix_report_tgf_tgf'), 'report_tgf', ['tgf'], unique=False)
    op.create_index(op.f('ix_report_tgf_tgf_ekat'), 'report_tgf', ['tgf_ekat'], unique=False)
    op.create_index(op.f('ix_report_tgf_tgf_hmao'), 'report_tgf', ['tgf_hmao'], unique=False)
    op.create_index(op.f('ix_report_tgf_tgf_kras'), 'report_tgf', ['tgf_kras'], unique=False)
    op.create_index(op.f('ix_report_tgf_tgf_kurgan'), 'report_tgf', ['tgf_kurgan'], unique=False)
    op.create_index(op.f('ix_report_tgf_tgf_more'), 'report_tgf', ['tgf_more'], unique=False)
    op.create_index(op.f('ix_report_tgf_tgf_novo'), 'report_tgf', ['tgf_novo'], unique=False)
    op.create_index(op.f('ix_report_tgf_tgf_omsk'), 'report_tgf', ['tgf_omsk'], unique=False)
    op.create_index(op.f('ix_report_tgf_tgf_tmn'), 'report_tgf', ['tgf_tmn'], unique=False)
    op.create_index(op.f('ix_report_tgf_tgf_tomsk'), 'report_tgf', ['tgf_tomsk'], unique=False)
    op.create_index(op.f('ix_report_tgf_tgf_ynao'), 'report_tgf', ['tgf_ynao'], unique=False)
    op.create_index(op.f('ix_report_tgf_vid_rab'), 'report_tgf', ['vid_rab'], unique=False)
    op.create_index(op.f('ix_report_tgf_year_int'), 'report_tgf', ['year_int'], unique=False)
    op.create_index(op.f('ix_report_tgf_year_str'), 'report_tgf', ['year_str'], unique=False)
    op.create_index(op.f('ix_report_tgf_zsniigg_report'), 'report_tgf', ['zsniigg_report'], unique=False)
    # ### end Alembic commands ###
    op.alter_column('file', 'f_root',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Источник',
               existing_nullable=True)
    op.alter_column('file', 'f_path',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Полный путь к файлу',
               existing_nullable=True)
    op.alter_column('file', 'f_folder',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Папка с файлом',
               existing_nullable=True)
    op.alter_column('file', 'f_name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Имя файла полное',
               existing_nullable=True)
    op.alter_column('file', 'f_ext',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Расширение',
               existing_nullable=True)
    op.alter_column('file', 'f_size',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='Размер',
               existing_nullable=True)
    op.alter_column('file', 'f_ctime',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Дата создания',
               existing_nullable=True)
    op.alter_column('file', 'f_mtime',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Дата модификации',
               existing_nullable=True)
    op.alter_column('file', 'f_atime',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Дата доступа',
               existing_nullable=True)
    op.alter_column('file', 'f_path_md5',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Хеш пути',
               existing_nullable=True)
    op.alter_column('file', 'f_text',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Текст',
               existing_nullable=True)
    op.alter_column('file', 'ngp',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='НГ Провинция',
               existing_nullable=True)
    op.alter_column('file', 'ngo',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='НГ Область',
               existing_nullable=True)
    op.alter_column('file', 'ngr',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='НГ Район',
               existing_nullable=True)
    op.alter_column('file', 'field',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Месторождение',
               existing_nullable=True)
    op.alter_column('file', 'areaoil',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Площадь',
               existing_nullable=True)
    op.alter_column('file', 'lu',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Лицензионный участок',
               existing_nullable=True)
    op.alter_column('file', 'lu_num',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Номер ЛУ',
               existing_nullable=True)
    op.alter_column('file', 'well',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Скважина',
               existing_nullable=True)
    op.alter_column('file', 'lat',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Координаты - lat',
               existing_nullable=True)
    op.alter_column('file', 'lon',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Координаты  - lon',
               existing_nullable=True)
    op.alter_column('file', 'report_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Идентификатор отчета',
               existing_nullable=True)
    op.alter_column('file', 'report_name',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Имя отчета',
               existing_nullable=True)
    op.alter_column('file', 'report_text',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Текст отчета',
               existing_nullable=True)
    op.alter_column('file', 'report_author',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Автор отчета',
               existing_nullable=True)
    op.alter_column('file', 'report_year',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Дата отчета',
               existing_nullable=True)
    op.alter_column('file', 'report_tgf',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='ТГФ',
               existing_nullable=True)
    op.alter_column('file', 'dog_zakaz',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Договор',
               existing_nullable=True)
    op.alter_column('file', 'dog_name',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Название договора',
               existing_nullable=True)
    op.alter_column('file', 'dog_num',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Номер договора',
               existing_nullable=True)
    op.alter_column('file', 'dog_date',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Дата договора',
               existing_nullable=True)
    op.alter_column('file', 'dog_isp',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Исполнитель',
               existing_nullable=True)
    op.alter_column('file', 'dog_rep',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Отчет по договору',
               existing_nullable=True)
    op.alter_column('file', 'dog_prikaz',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Приказ',
               existing_nullable=True)
    op.alter_column('file', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Удален',
               existing_nullable=True)
    op.alter_column('file', 'lastupdate',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Дата последнего обновления',
               existing_nullable=True)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_tgf_zsniigg_report'), table_name='report_tgf')
    op.drop_index(op.f('ix_report_tgf_year_str'), table_name='report_tgf')
    op.drop_index(op.f('ix_report_tgf_year_int'), table_name='report_tgf')
    op.drop_index(op.f('ix_report_tgf_vid_rab'), table_name='report_tgf')
    op.drop_index(op.f('ix_report_tgf_tgf_ynao'), table_name='report_tgf')
    op.drop_index(op.f('ix_report_tgf_tgf_tomsk'), table_name='report_tgf')
    op.drop_index(op.f('ix_report_tgf_tgf_tmn'), table_name='report_tgf')
    op.drop_index(op.f('ix_report_tgf_tgf_omsk'), table_name='report_tgf')
    op.drop_index(op.f('ix_report_tgf_tgf_novo'), table_name='report_tgf')
    op.drop_index(op.f('ix_report_tgf_tgf_more'), table_name='report_tgf')
    op.drop_index(op.f('ix_report_tgf_tgf_kurgan'), table_name='report_tgf')
    op.drop_index(op.f('ix_report_tgf_tgf_kras'), table_name='report_tgf')
    op.drop_index(op.f('ix_report_tgf_tgf_hmao'), table_name='report_tgf')
    op.drop_index(op.f('ix_report_tgf_tgf_ekat'), table_name='report_tgf')
    op.drop_index(op.f('ix_report_tgf_tgf'), table_name='report_tgf')
    op.drop_index(op.f('ix_report_tgf_territory_name'), table_name='report_tgf')
    op.drop_index(op.f('ix_report_tgf_subrf_name'), table_name='report_tgf')
    op.drop_index(op.f('ix_report_tgf_rgf'), table_name='report_tgf')
    op.drop_index(op.f('ix_report_tgf_report_name'), table_name='report_tgf')
    op.drop_index(op.f('ix_report_tgf_pi_name'), table_name='report_tgf')
    op.drop_index(op.f('ix_report_tgf_part_name'), table_name='report_tgf')
    op.drop_index(op.f('ix_report_tgf_org_name'), table_name='report_tgf')
    op.drop_index(op.f('ix_report_tgf_lu'), table_name='report_tgf')
    op.drop_index(op.f('ix_report_tgf_list_name'), table_name='report_tgf')
    op.drop_index(op.f('ix_report_tgf_inf_report'), table_name='report_tgf')
    op.drop_index(op.f('ix_report_tgf_folder_short'), table_name='report_tgf')
    op.drop_index(op.f('ix_report_tgf_folder_root'), table_name='report_tgf')
    op.drop_index(op.f('ix_report_tgf_folder_name'), table_name='report_tgf')
    op.drop_index(op.f('ix_report_tgf_folder_link'), table_name='report_tgf')
    op.drop_index(op.f('ix_report_tgf_fin_name'), table_name='report_tgf')
    op.drop_index(op.f('ix_report_tgf_field'), table_name='report_tgf')
    op.drop_index(op.f('ix_report_tgf_comments'), table_name='report_tgf')
    op.drop_index(op.f('ix_report_tgf_author_name'), table_name='report_tgf')
    op.drop_index(op.f('ix_report_tgf_areaoil'), table_name='report_tgf')
    op.drop_table('report_tgf')
    # ### end Alembic commands ###
